config/routes.rb
Rails.application.routes.draw do  
  get 'estado_medidors/index_ruta' => 'estado_medidors#index_ruta', as: :index_ruta
  resources :users
  resources :roles
  resources :usuarios
  devise_for :users, :path => 'user'
  get 'index/index'

  root 'index#index'

  get 'index' => 'index#index'
  get 'personas/find_persona/:tipo_documento_id/:nro_documento' => 'personas#find_persona', as: :find_persona
  get 'usuarios/get_medidores/:usuario_id' => 'usuarios#get_medidores', as: :get_medidores

  post 'restful/signin' => 'restful#signin', as: :signin
  post 'restful/signup' => 'restful#signup', as: :signup
  post 'restful/descargar_ruta' => 'restful#descargar_ruta', as: :descargar_ruta
  post 'restful/guardar_medicion' => 'restful#guardar_medicion', as: :guardar_medicion

  get 'restful/chequear_ruta' => 'restful#chequear_ruta', as: :chequear_ruta 
  

end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :user_roles, :foreign_key => 'role_id', :class_name => 'UserRole'
  	has_many :users, :through => :user_roles

  	validates :descripcion, :presence => { :message => "Debe completar el campo Descripción" }
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Se ha creado un nuevo Rol.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Se ha actualizado el Rol.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Se ha eliminado el Rol.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:descripcion)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
  def build_role_list(partialFile='')
    list_items = ""
    roleList = Role.all
    for role in roleList
      list_items += build_role_list_item(role ,partialFile)
    end
    output = list_items
    return output.html_safe
  end

  def build_role_list_item(local_role,partialFile)
    role_list_output = ""
  	#role_list_output += render :partial => '/roles/ul', :locals => { :list_items => local_role }
    output = render( :partial => partialFile, :locals => {:current_role => local_role})
    return output.html_safe
  end
end

app/views/roles/_form.html.erb
<%= form_for(@role, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @role.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
      <h5><b><%= fa_icon "exclamation-circle", text: "Atención! Ocurrieron los siguientes errores" %></b></h5>
      <ul>
      <% @role.errors.messages.values.each do |msg| %>
        <%msg.each do  |m| %>
          <li><%= m %></li>
        <%end %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :descripcion, "Descripción", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :descripcion, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary", value: "Guardar"%>
    </div>
  </div>
<% end %>

app/views/roles/edit.html.erb
<div class="page-header">
  <%= link_to roles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to @role, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Ver
  <% end %>
  <h4>Editar Rol</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to roles_path do %>
        <%= fa_icon "universal-access", text: "Roles" %>
    <% end %>
  </li>
  <li class="active">
    Editar Rol
  </li>
</ol>

<%= render 'form' %>

app/views/roles/index.html.erb
<div class="page-header">
  <%= link_to new_role_path, class: 'btn btn-primary' do %>
    <%= fa_icon "plus", text: "Nuevo Rol" %>
  <% end %>
  <h4>Listado de Roles</h4>
</div>
<ol class="breadcrumb">
  <li class="active">
    <%= fa_icon "universal-access", text: "Roles" %>
  </li>
</ol>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Descripción</th>
            <th class="col-md-2">&nbsp;</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @roles) do |role| %>
      <td><%= role.descripcion %></td>
      <td class="text-center">
        <%= link_to role, class: 'btn btn-sm btn-default' do %>
          <span class="glyphicon glyphicon-search"></span>
        <% end %>
        <%= link_to edit_role_path(role), class: 'btn btn-sm btn-default' do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
        <%= link_to role, class: 'btn btn-sm btn-danger',method: :delete, data: { confirm: '¿Está seguro?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </td>      
      <% end %>
    </tbody>
  </table>
</div>

app/views/roles/new.html.erb
<div class="page-header">
  <%= link_to roles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <h4>Nuevo Rol</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to roles_path do %>
        <%= fa_icon "universal-access", text: "Roles" %>
    <% end %>
  </li>
  <li class="active">
    Nuevo Rol
  </li>
</ol>

<%= render 'form' %>

app/views/roles/show.html.erb
<div class="page-header">
  <%= link_to roles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to edit_role_path(@role), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h4>Ver Rol</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to roles_path do %>
        <%= fa_icon "universal-access", text: "Roles" %>
    <% end %>
  </li>
  <li class="active">
    Ver Rol
  </li>
</ol>

<dl class="dl-horizontal">
  <dt>Descripción:</dt>
  <dd><%= @role.descripcion %></dd>

</dl>